export * from './HomePage'
export * from './LoginPage'
export * from './CRUDMascotasPage'
// export * from './Footer'
export * from './CRUDUsuariosPage'
export * from './EstadoAdopcionesPage'
export * from './MascotasGaleriaPage'
export * from './PublicacionCompartidaPage'